version: '3.8'
services:
  backend:
    build: backend/
    restart: always
    ports:
      - '8301:3000'
  frontend:
    build: frontend/
    ports:
      - '8300:3000'
    restart: always
  db:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=nopestradamus
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/:/docker-entrypoint-initdb.d/
volumes:
  db:
