services:
  frontend:
    build:
      dockerfile: ./Dockerfile.frontend
    ports:
      - '8300:3000'
    restart: always
  cron:
    build:
      dockerfile: ./Dockerfile.cron
    restart: always
  db:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=nopestradamus
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/:/docker-entrypoint-initdb.d/
volumes:
  db:
